site_name: CS Tools
site_url: https://thoughtspot.github.io/cs_tools/
site_description: >-
  Scale your ThoughtSpot adoption with tools created by the ThoughtSpot Solutions Consulting organization.

repo_name: thoughtspot/cs_tools
repo_url: https://github.com/thoughtspot/cs_tools

copyright: Copyright &copy; 2021 ThoughtSpot Inc. All Rights Reserved

docs_dir: docs

theme:
  name: material
  logo: assets/images/thoughtspot-logo-white.png
  custom_dir: docs/.overrides
  features:
    - announce.dismiss
    - content.code.copy
    - content.code.annotate
    - navigation.footer
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.instant
  favicon: assets/images/favicon.svg
  icon:
    repo: fontawesome/brands/github
  font:
    text: Optimo-Plain
    code: BB Roller Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: thoughtspot-light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

extra:
  # Could investigate in order to offer a beta docs page.
  #
  # version:
  #   provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/thoughtspot/cs_tools
      name: find us on github

    - icon: fontawesome/solid/paper-plane
      link: mailto:nicholas.cooper@thoughtspot.com
      name: email the team

markdown_extensions:
  - attr_list
  - admonition
  - cs_tools.md_ext.screenshotter
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - glightbox
  - open-in-new-tab
  - redirects:
      redirect_maps:
        'get/bootstrapper.md': 'https://raw.githubusercontent.com/thoughtspot/cs_tools/master/cs_tools/updater/_bootstrapper.py'

nav:
  - Home: index.md
  - Tutorial:
    - "Getting Started": tutorial/intro.md
    - "Install & Upgrade": tutorial/install.md
    - "Setup a Config File": tutorial/config.md
    - "Run the Archiver tool": tutorial/archiver.md
    - "Using Syncers": tutorial/syncer.md
    - "Schedule the Archiver": tutorial/schedule.md
  - Tools:
    - tools/index.md
    - Archiver: tools/archiver/README.md
    - Bulk Deleter: tools/bulk-deleter/README.md
    - Bulk Sharing: tools/bulk-sharing/README.md
    - Extractor: tools/extractor/README.md
    - Falcon Sharding: tools/falcon-sharding/README.md
    - Remote TQL: tools/rtql/README.md
    - Remote tsload: tools/rtsload/README.md
    - Git: tools/git/README.md
    - Scriptability: tools/scriptability/README.md
    - Searchable: tools/searchable/README.md
    - User Management: tools/user-management/README.md
  - Syncers:
    - "What's a Syncer?": syncer/what-is.md
    # - Amazon Redshift: syncer/redshift.md
    - CSV: syncer/csv.md
    # - Databricks: syncer/databricks.md
    # - Google BigQuery: syncer/bigquery.md
    - Google Sheets: syncer/gsheets.md
    - JSON: syncer/json.md
    - Microsoft Excel: syncer/excel.md
    - Parquet: syncer/parquet.md
    # - Postgres: syncer/postgres.md
    - Snowflake: syncer/snowflake.md
    - SQLite: syncer/sqlite.md
    - Starburst: syncer/starburst.md
    - ThoughtSpot Falcon: syncer/falcon.md
    - Trino: syncer/trino.md
  - Changelog:
    - v1.5.0: changelog/1.5.0.md
    - v1.4.0: changelog/1.4.0.md
    - v1.3.0: changelog/1.3.0.md
    - v1.2.0: changelog/1.2.0.md
    - v1.1.0: changelog/1.1.0.md
    - v1.0.0: changelog/1.0.0.md
