name: "📜 Incorrect Documentation"
description: Found something wrong with documentation? Report it here.
labels: [documentation, bug]
body:
  - type: markdown
    attributes:
      value: >-
        ## *Thanks for your interest in cs_tools!* :tada:

        This project is maintained by the Solutions Consulting organization at ThoughtSpot. It is our passion project!

        While we make every opportunity to keep up to date, resolve issues, well-document our tools, and provide a great
        experience..

        If you find something is wrong with your ThoughtSpot cluster, please open a [Support Case](https://community.thoughtspot.com/s/contactsupport).

        If you wish you had a feature in ThoughtSpot, please open a [__Product Idea__](https://community.thoughtspot.com/s/ideas).

  - type: checkboxes
    id: checks
    attributes:
      label: First Stop
      description: Please confirm and check all the following options.
      options:
        - label: I have read and agreed to the ThoughtSpot Dev Tools EULA.
          required: true

        - label: >-
            I understand that if I have a critical issue with ThoughtSpot, I should reach out to my designated Account Executive and Solutions Consultant team instead of cs_tools.
          required: true

        - label: I searched the cs_tools documentation, with the integrated search.
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: >-
        What is wrong with the docs?

        Write a short description telling us what the docs are missing, a link to where you found a typo, or if you thought something was generally confusing.

    validations:
      required: true
