name: "📜 Incorrect Documentation"
description: Found something wrong with documentation? Report it here.
labels: [documentation, bug]
body:
  - type: markdown
    attributes:
      value: >-
        ## *Thanks for your interest in cs_tools!* :tada:

        While this project is maintained by the customer team at __ThoughtSpot__, it is our passion project!

        If you are experiencing an issue with your ThoughtSpot cluster, please open a [__Support Case__](https://community.thoughtspot.com/s/article/How-to-submit-a-ThoughtSpot-Support-Case).

        If you wish you had a feature in ThoughtSpot, please open a [__Product Idea__](https://community.thoughtspot.com/s/ideas).

  - type: checkboxes
    id: checks
    attributes:
      label: First Stop
      description: Please confirm and check all the following options.
      options:
        - label: I have read and agreed to the ThoughtSpot LICENSE.
          required: true

        - label: >-
            I understand that if I have a critical issue with __ThoughtSpot__, I should reach out to my designated __Account Executive__ and __Customer Success Manager__ instead of `cs_tools`.
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: >-
        What is wrong with the docs?

        Write a short description telling us what the docs are missing, a link to where you found a typo, or if you thought something was generally confusing.

    validations:
      required: true
