name: "🐛 Bug Report"
description: Found something wrong with cs_tools? Report it here.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: >-
        ## *Thanks for your interest in cs_tools!* :tada:

        This project is maintained by the Solutions Consulting organization at ThoughtSpot. It is our passion project!

        While we make every opportunity to keep up to date, resolve issues, well-document our tools, and provide a great
        experience..

        If you find something is wrong with your ThoughtSpot cluster, please open a [Support Case](https://community.thoughtspot.com/s/contactsupport).

        If you wish you had a feature in ThoughtSpot, please open a [__Product Idea__](https://community.thoughtspot.com/s/ideas).

  - type: checkboxes
    id: checks
    attributes:
      label: First Stop
      description: Please confirm and check all the following options.
      options:
        - label: I have read and agreed to the ThoughtSpot Dev Tools EULA.
          required: true

        - label: >-
            I understand that if I have a critical issue with ThoughtSpot, I should reach out to my designated Account Executive and Solutions Consultant team instead of cs_tools.
          required: true

        - label: I searched the cs_tools documentation, with the integrated search.
          required: true

  - type: textarea
    id: platform-configuration
    attributes:
      label: Platform Configuration
      description: Please include the output of `cs_tools self info --anonymous --directory .`.
      placeholder: Drag the cs-tools-info-YYYY-mm-dd.svg into this window.

    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: >-
        What is the problem, question, or error?

        Write a short description telling us what you are doing, what you expect to
        happen, and what is currently happening.

        If we can copy it, run it, and see it right away, there's a much higher chance we'll be able to help you.

    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Need to upload log files securely?
      description: >-
        Run the following command.

        `cs_tools logs report --latest 5`
        
        Then use the secure file share link below, which routes to the CS Tools team directly.
        https://thoughtspot.egnyte.com/ul/1bK0dz05L6
