name: Deploy docs to GH Pages

on:
  push:
    branches:
      - master

jobs:
 build:

    env:
      CS_TOOLS_THOUGHTSPOT__URL: ${{ secrets.THOUGHTSPOT_URL }}
      CS_TOOLS_THOUGHTSPOT__USERNAME: ${{ secrets.THOUGHTSPOT_USERNAME }}
      CS_TOOLS_THOUGHTSPOT__SECRET_KEY: ${{ secrets.THOUGHTSPOT_SECRET_KEY }}
      CS_TOOLS_TEMP_DIR: /tmp

    runs-on: ubuntu-latest
    steps:
      # CHECKOUT REPOSITORY.
      - name: Checkout repository
        uses: actions/checkout@v3

      # SETUP PYTHON.
      - name: Set up Python
        uses: actions/setup-python@v5

      # UPDATE PIP.
      - name: Ensure pip is up to date.
        run: python -m pip install --upgrade pip

      # INSTALL THE LATEST VERSION OF THE CS Tools PROJECT.
      - name: Install Python dependencies
        run: python -m pip install -e ".[docs]"

      # BUILD THE DOCS.
      - name: Build MkDocs Documentation
        run: mkdocs build --clean
        env:
          # FORCE THE TERMINAL TO THINK IT'S 130 COLUMNS WIDE.
          COLUMNS: "130"
      
      # DEPLOY THE DOCS.
      - name: Deploy Documentation
        run: mkdocs gh-deploy --force
