name: Deploy docs to GH Pages

on:
  push:
    branches:
      - master

jobs:
 build:

    env:
      CS_TOOLS_THOUGHTSPOT__URL: ${{ secrets.THOUGHTSPOT_URL }}
      CS_TOOLS_THOUGHTSPOT__USERNAME: ${{ secrets.THOUGHTSPOT_USERNAME }}
      CS_TOOLS_THOUGHTSPOT__SECRET_KEY: ${{ secrets.THOUGHTSPOT_SECRET_KEY }}

    runs-on: ubuntu-latest
    steps:
      # SETUP PYTHON.
      - name: Set up Python
        uses: actions/setup-python@v5
      
      # UPDATE PIP.
      - name: Ensure pip is up to date.
        run: python -m pip install --upgrade pip

      # INSTALL THE LATEST VERSION OF THE CS Tools PROJECT.
      - name: Install Python dependencies
        run: python -m pip install -e .[docs]

      # BUILD THE DOCS.
      - name: Build MkDocs Documentation
        run: mkdocs build
      
      # DEPLOY THE DOCS.
      - name: Deploy Documentation
        run: mkdocs gh-deploy --force
