name: Deploy docs to GH Pages

on:
  push:
    branches:
      - master

jobs:
 build:

    env:
      CS_TOOLS_THOUGHTSPOT__URL: https://dogfood.thoughtspot.cloud
      CS_TOOLS_THOUGHTSPOT__USERNAME: FakeUser
      CS_TOOLS_THOUGHTSPOT__SECRET_KEY: 00000000-0000-0000-0000-000000000000

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install Python dependencies
        run: pip install -e .[docs]

      - name: Build and Deploy Documentation
        run: mkdocs build

      - name: Deploy Documentation
        run: mkdocs gh-deploy --force
